### ISSUE TITLE
upgrading within Angular 9 

### ISSUE THREAD

**Issue by JosVermoesen** [maxime1jacquet/npm-directives#10]
Upgrading exsisting Angular9 app within version 9;
ng update @angular/cli@9 @angular/core@9

Gives failed warning:
Package "ngx-simple-countdown" has an incompatible peer dependency to "@angular/core" (requires "^7.0.0" (extended), would install "9.1.9")

Just to mention.  Your tool keeps working fine.
Greetings from Belgium, Jos

**Comment by maxime1jacquet** [comment]
Hey !

Thank for your message, 
I will improve this package soon !

**Comment by maxime1jacquet** [comment]
This package is update ! thanks for you message
