### ISSUE TITLE
HideUnit option from documentation is missing

### ISSUE THREAD

**Issue by nulee** [maxime1jacquet/npm-directives#21]
Hey there!

The _**hideUnit**_ option mentioned in documentation is not available anymore.
![image](https://user-images.githubusercontent.com/33671369/126293561-c84de3f0-57c9-41b8-856e-93f8a862bb87.png)

It causes the following error: _**Can't bind to 'hideUnit' since it isn't a known property of 'div'.**_, which is to be expected as the option is not implemented in the [directive](https://github.com/maxime1jacquet/npm-directives/blob/master/projects/ngx-simple-countdown/src/lib/ngx-simple-countdown.directive.ts) at all.

**Comment by maxime1jacquet** [comment]
Hello, thank for your feedback. 

I tried this feature but it was not good, so i remove the code but not the documentation.
I will remove this part of documentation.

Thank you
