### ISSUE TITLE
Method .initSlider() not found

### ISSUE THREAD

**Issue by Aprilia1982** [maxime1jacquet/npm-directives#45]
Hi, 
i would like to use the slider with ngfor. Unfortunatly the method this.tinySlider.initSlider() is not found. Do you have any ideas for that?
Jan

**Comment by maxime1jacquet** [comment]
Hello, 

Can you show me all of your component code ? Did you add type TinySliderInstance on the ViewChild ? 

And if you try to put the ViewChild as any, the behavior it’s good ?

**Comment by maxime1jacquet** [comment]
I see a issue on my documentation . 
To install dependancies it’s : 
´´´
npm i ngx-wrapper-tiny-slider
´´´

It’s a mistake, maybe you installed another package

**Comment by Aprilia1982** [comment]
Yes, it works. Thanks for quick response.
